aya-lang/aya

- src/aya/Aya.java
On windows, the ayaDir will contain `\` for example: `D:\Aya\bin\`.
These will be treated as an escape character by the String Parser and create nonsense.
The fix is to escape these characters, resulting in e.g. `D:\\Aya\\bin\\`
> resolve escape char error when loading ayarc

- src/aya/ext/graphics/Canvas.java
Currently, when BufferStrategy::contentsLost occurs, Aya enters an infinite loop.  
From the javadoc for contentsLost: 'Returns whether the drawing buffer was lost since the last call to getDrawGraphics.'  
As far as I can tell, repainting does not cause the BufferStrategy to create a new Graphics instance / revalidate - so it remains `true`.
Removing the BufferStrategy showed no significant performance difference on my end and resolves this issue.
Alternatively, I have tried drawing to the BufferStrategy drawGraphics instead of the BufferedImage graphics, but that also gave no significant performance difference, so I've opted for the solution that removes code rather than adding some.
> Fix: Aya "randomly" permanently freezes on startup when using Canvas

- examples/canvas/attractor.aya
- examples/canvas/color_typewriter.aya
- examples/canvas/mouse.aya
- src/aya/ext/graphics/Canvas.java
- src/aya/obj/list/List.java
- std/canvas.aya
- Standard library
- Wrap mouse & keyboard `:{graphics.*}` functions in `canvas`
- Examples
- [new] Simple mouse input (`canvas/mouse.aya`)
- [new] Color Typewriter (`canvas/color_typewriter.aya`) 
- [updated] Move attractor with mouse (`canvas/attractor.aya`)
- Bug fixes
- Fix uncaught index error when setting index of list
- Fix `NullPointerException` thrown when accessing canvas input before displaying the canvas
> Mouse and keyboard examples

- src/aya/instruction/op/ColonOps.java
Dev test:
```
aya> "value" "key" {,} :D
{,
"value":key;
} 
aya> "value" ::sym_key {,} :D
{,
"value":sym_key;
} 
aya> "value" ["list" ::of "keys"] {,} :D
{,
"value":of;
"value":keys;
"value":list;
} 
```
Resolves #82
> fix #82 ( `:D` Operator with String key)

- base/exception.aya
- base/list.aya
- base/sym.aya
- src/aya/ext/graphics/Canvas.java
- src/aya/ext/image/ReadImageInstruction.java
- src/aya/ext/la/MatMulInstruction.java
- src/aya/instruction/op/ColonOps.java
- src/aya/instruction/op/DotOps.java
- src/aya/instruction/op/MiscOps.java
- src/aya/instruction/op/Ops.java
- src/aya/obj/Obj.java
- src/aya/obj/list/GenericList.java
- src/aya/obj/list/List.java
- src/aya/obj/list/ListAlgorithms.java
- src/aya/obj/list/ListImpl.java
- src/aya/obj/list/ListRangeUtils.java
- src/aya/obj/list/Str.java
- src/aya/obj/list/numberlist/DoubleList.java
- src/aya/obj/list/numberlist/NumberItemList.java
- src/aya/obj/list/numberlist/NumberList.java
- src/aya/obj/number/BaseConversion.java
- src/test/obj/list/numberlist/NumberItemListTest.java
Requires #78 
Adds an optimized `ListImpl` for lists of doubles only.
Math operations happen directly on the data in `double[]` and no longer need to use `Number` wrappers or `NumberMath`. The result is much faster vectorized operations.  
Additionally, many of the algorithms (slice, rotate, ect.) have been optimized.
Still working on some proper benchmarks but here are some examples:
```
aya-0.3> 10000R:l; {{l 1+ 2- 3/ 4* 1.05^ ;} 10000 %}.time
5788 .# 5.8 seconds
aya-0.4> 10000R:l; {{l 1+ 2- 3/ 4* 1.05^ ;} 10000 %}.time
2186 .# 2.2 seconds
```
> WIP: `ListImpl` for `double[]`

- std/io.aya
Currently `_isabs` does not work for paths in drives that are not the Aya's root drive.
E.g. `"E:\\myFile.txt" path._isabs` -> `0` (wrong)
While `"D:\\myFile.txt" path._isabs` -> `1` (right)
For absolute paths `__str__` is incorrect on windows:
`"D:\\myFile.txt" path! P` -> `"/D:/myFile.txt"` (the leading / is the problem here, otherwise windows doesn't care about \ vs /)
I also removed `path.filesplit`, since that does not seem to be used anymore.
---
Note: I opted for a very simple _isabs check.
If you look at the [[Java WinNTFileSystem isAbsolute Method]](https://github.com/stain/jdk8u/blob/master/src/windows/classes/java/io/WinNTFileSystem.java#L294) you'll notice that a "proper" check is quite the headache. ('getPrefixLength' is the result of …
> Fix std/io '_isabs' and '__str__' for windows

- src/aya/instruction/op/DotOps.java
- src/aya/obj/list/GenericList.java
- src/aya/obj/list/List.java
- src/aya/obj/list/ListImpl.java
- src/aya/obj/list/Permutations.java
- src/aya/obj/list/Str.java
- src/aya/obj/list/numberlist/DoubleList.java
- src/aya/obj/list/numberlist/NumberItemList.java
New operator `.Z`: generate all permutations of  a list
```
aya> "abc" .Z
[ "abc" "bac" "cab" "acb" "bca" "cba" ] 
aya> [1 2 3] .Z
[
[ 1 2 3 ]
[ 2 1 3 ]
[ 3 1 2 ]
[ 1 3 2 ]
[ 2 3 1 ]
[ 3 2 1 ]
] 
aya> [1 'a {}] .Z
[
[ 1 'a {} ]
[ 'a 1 {} ]
[ {} 1 'a ]
[ 1 {} 'a ]
[ 'a {} 1 ]
[ {} 'a 1 ]
] 
```
> Add .Z operator for computing permutations

- src/aya/instruction/op/DotOps.java
It seems this commit changed the order of arguments without updating the docs.
https://github.com/aya-lang/aya/commit/ff1a162094ba3fa784e7292fce3f13ee15250af2
Usages like https://github.com/aya-lang/aya/blob/53542a60a22de71af90e81ca66eed560722d7ea1/base/importlib.aya#L74
were updated though, so I'm assuming it's *just* the docs that are wrong.
> fix docs for regex replace operator (.&)

- src/aya/AyaPrefs.java
- src/aya/InteractiveAya.java
- src/aya/ext/graphics/instruction/SaveGraphicsInstruction.java
- src/aya/ext/plot/FreeChartInterface.java
- src/aya/ext/sys/SystemInstructionStore.java
- src/aya/instruction/op/DotOps.java
- src/aya/instruction/op/Ops.java
- src/aya/util/FileUtils.java
I noticed that while `G` works great, `.G` does not.
Example: `"C:\abs\file.txt" :& G \ "_2"+ 0 .G` (which should copy the file content into `C:\abs\file.txt_2`)
instead results in
```
io_err at .G: unable to use resource D:\tools\Aya\bin_v4_rc1\C:\abs\file.txt_2. Invalid path
in .G .. }
```
So I had a look at all the uses of AyaPrefs.getWorkingDir() and updated those.
**Tests**
```
.# Windows Tests
"C:/abs/test.txt" :& G \ "_2"+ 0 .G       .# correctly copies from C:/abs/test.txt     to C:/abs/test.txt_2        preserving \r\n
"test.txt"        :& G \ "_2"+ 0 .G       .# correctly copies from <workDir>/test.txt  to <workDir>/test.txt_2 preserving \r\n
"/test.txt"       :& G \ "_2"+ 0 .G       .# behaves identical to "test.txt" on Windows (good)
.# WSL Ubuntu Tests
"C:/abs/test.txt" …
```
> Refactor FileSystem handling (fix absolute paths on Windows)

- src/aya/instruction/op/DotOps.java
I've noticed that `["c" "a" "b"] C` works
however `["c" "a" "b"] {} .C` didn't work.
Attempting to sort different key types still results in the correct error:
```
.C: all objects must be comparable to each other
["c" "a" 2] {} .C
~~~~~~~~~~~~~~~~^
Function call traceback:
```
> Allow sorting Strings with OP_Dot_SortUsing

- src/aya/InteractiveAya.java
While trying to run aya-digit on Windows I got a funny Error.
```
io_err at :F: unable to use resource D:\aya
orks\aya-digit\interactive.aya. Illegal char <
```
For my path `D:\aya\forks\aya-digit\`
---
All other manually created `:F` instructions seem to handle this correctly already, so I just mirrored that.
> Fix StartupScript-Paths containing escape sequences failing on Windows

- src/aya/AyaPrefs.java
- src/aya/ext/fstream/FStreamManager.java
- src/aya/ext/image/ReadImageInstruction.java
- src/aya/ext/image/WriteImageInstruction.java
- src/aya/ext/sys/SystemInstructionStore.java
- test/filesystem.aya
While trying to use aya-digit I noticed that `"model.json" json.load` fails on windows.
I've used `FileUtils.resolveFile` where it seemed appropriate. (relates to #93 )
I initially thought this fix only applied to windows, but after testing on Ubuntu, it appears Aya also behaves oddly on Linux?
**(Stop me if the assumptions in my tests are just plain wrong)**
The primary cause of Linux weirdness seems to come from my shell having a different working directory than the one I pass to Aya.
'Actual output' indicates the behaviour I am seeing with the current Version of Aya.
'Expected output' is the behaviour using the changes of this PR.
---
test.aya:
```
"dir1" :{sys.mkdir}
"./dir1" :{sys.cd}
"dir2" :{sys.mkdir}
```
`~/dir3$ java -jar /path/to/aya.jar /path/to/test /path/to/test/test.aya` …
> Fix File-resolution on Windows

- src/aya/util/VectorizedFunctions.java
When updating the broadcasting rules in #97, the rules were not properly applied to the `NumberList` optimized code. This means that if using a `NumberList` it would default to standard single item processing. This would lead to the correct result but be much slower that using the `NumberList` operator.
This update adds the additional cases to the numberlist optimization.
When testing broadcasting across arrays with a shape of `[3 35000]` this fix led to a **~100x speedup**.
> Broadcasting rules are properly applied to length 1 `NumberList`s

- src/aya/ext/graphics/GraphicsInstructionStore.java
- src/aya/ext/graphics/instruction/PointsGraphicsInstruction.java
- src/aya/util/BlockReader.java
- std/canvas.aya
Add a graphics instruction for drawing a batch of points. This instruction gives roughly a 5-7x speedup over looping through each point individually. 
With this instruction we can render all 35K points of the Stanford bunny at in 10ms (previously 50ms-70ms)
[Screencast from 2024-11-28 12-29-59.webm](https://github.com/user-attachments/assets/660ba2fe-30d4-4edf-9344-cd22f763ddc9)
> Add graphics instruction for drawing a batch of points

- pom.xml
- src/aya/InteractiveAya.java
- src/web/AyaWeb.java
This makes building the fat-jar and web files optional.
This also allowed me to move 'creating the release aya.zip' from `verify` into `package` - which seems more standard.
- use `-P !desktop` to just compile / run tests
- use `mvn package` to create `aya.zip`
- use `mvn package -P web` to create `aya.js` and `aya.stdlib.js`
- use `mvn package -P desktop,web` to do both
⚠in direct conflict with #119 (pick one)
---
This also includes some opinionated changes:
- use lambdas instead of anonymous classes in `AyaWeb.java`
- keep the `web/**` files in the fat jar, since they shouldn't cause any issues.
> Build restructure option 2 : optional execution using profiles

- pom.xml
- src/aya/StaticData.java
Since [v0.5.0 is now released](https://github.com/aya-lang/aya/releases/tag/v0.5.0), master will track the development of v0.6.0. I have updated the version strings to use the [maven snapshot convention](https://maven.apache.org/guides/getting-started/#What_is_a_SNAPSHOT_version.3F). 
The version is now `0.6.0-SNAPSHOT`
> Update version to 0.6.0 snapshot

- src/aya/ext/sys/SystemInstructionStore.java
Add path operators for checking if a path is a directory and converting a path to a normalized (no `..` or `.`) absolute path
> Path ops: isdir and absolute

- src/aya/parser/Parser.java
- src/aya/parser/tokens/CurrentFileToken.java
Add operator for getting the path to the current file (M0)
Implemented as a parser token, the operator becomes the string literal during parse time
> Add operator for getting the path to the current file (M0)

- src/aya/ReprStream.java
- src/aya/obj/dict/Dict.java
- src/aya/obj/list/Str.java
Previously, when converting a dict to a string, string values in the dict (and string values of nested dicts, etc) would be truncated. This made it impossible to recover the full string unless manually iterating through the dict.
This change makes it so that `P` won't truncate string values when converting dicts to strings
> Don't truncate string values when converting dicts to strings

- build-scripts/run-aya-tests-build.xml
- src/aya/StaticData.java
- src/aya/instruction/named/NamedOperatorInstruction.java
- src/aya/parser/tokens/NamedOpToken.java
- test/lib/example/ExampleStore.java
- test/lib/example/aya.instruction.named.NamedInstructionStore
- test/lib/example/build.xml
- test/lib/lib.aya
- test/test.aya
I've found a good excuse to write an aya library and discovered some oversights in #111 
- StaticData no longer releases the classloader used to load libraries
- this avoids a ClassNotFoundException when libraries have multiple classes (such as `DataStorage` in the example library)
- NamedOpToken now no longer throws a ParserException for "undefined" namedOps
- libraries could be loaded at any time, so a ParserException does not make sense anymore
- instead, the opName is checked when the Instruction is executed
- to verify that this actually works, an example library is compiled and imported during the maven test phase
- (if you'd prefer, I can move the test/example library to `/examples` instead)
> Fix classloader and parser handling for libraries, add tests

- src/aya/ext/json/JSONUtils.java
- test/std/test_json.aya
- test/test.aya
Introduced by #113
The Json library now (sometimes) creates `BigDecimal`s when parsing decimals.
Example failure:
```
aya> "{test: 1.23}" :(json.loads)
Unsupported type: 1.23
"{test: 1.23}" :(json.loads)
~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Function call traceback:
```
> fix a regression when parsing Json with decimals

- src/aya/instruction/op/ColonOps.java
This would cause a crash due to trying to check if there was a shebang at the beginning of the file file:
```
aya> "" "empty_file.aya" 0 .G
aya> "empty_file.aya" :F
```
> Fix crash when attempting to load an empty file

- src/aya/InteractiveAya.java
- src/ui/AyaIDE.java
- src/ui/EditorWindow.java
- std/golf.aya
This PR adds several CLI arguments
A summary of the new options is available using the new `--help` argument
```
$ aya --help
aya v0.6.0-SNAPSHOT
aya
Running aya with no args will open the GUI IDE at the default working directory
Note: Default setting is GUI so that double clicking the jar from a file explorer opens the IDE
Use `aya <workingDir> -x` to open the GUI at a specified directory
aya <workingDir>
Open a command line REPL
aya <workingDir> <filename>
Run the file and exit
aya <workingDir> -<flags> <option1>
g: Import std/golf and bring all variables into scope
e: Run the expression given by <option1>
p: Run the package name given by <opion1>
i: Enter the REPL after finishing CLI tasks
x: Launch the GUI
If <option1> is an aya source file, run it
aya --help
Print this message.
aya …
```
> Refactor command line arguments; add additional options

- src/aya/instruction/op/DotOps.java
- test/filesystem.aya
As suggested in discord, I have changed `.G` to allow writing bytes.
I also allowed writing single characters and bytes for convenience.
Although performance-wise `fstream.O` should be preferred for that.
TypeErrors for the filename now show the correct argument and a message.
<table>
<tr>
<td><b>before</b></td>
<td><b>after</b></td>
</tr>
<tr>
<td><pre>
aya> "test" [1] 0 .G
Type error at (.G):
.	Expected ((ASN))
.	Received (0 )
.
.
"test" [1] 0 .G
~~~~~~~~~~~~~~^
Function call traceback:
</pre></td>
<td><pre>
aya> "test" [1] 0 .G
Type error at (.G):
.	filename is not a string
.	Expected ((SSN|CSN|LSN|NSN))
.	Received ([ 1 ] )
.
.
"test" [1] 0 .G
~~~~~~~~~~~~~~^
Function call traceback:
</td></pre>
</tr>
</table>
> Allow `.G` to write single bytes and lists of bytes to files

- src/aya/AyaThread.java
- src/aya/InteractiveAya.java
- src/ui/EditorWindow.java
Move blocking code out of editor window. All requests are processed in the same processing loop.
Fixes #108 
Test case:
Open editor window and run the following code:
```
import dialog
"test" dialog.alert
```
Note that requests are still processed in sequence by the main thread so only one alert box will appear at a time if you run the editor window multiple times. All inputs will be queued though
> Fix editor window deadlock

- examples/canvas/circles.aya
- examples/fibonacci.aya
- manual/blocks_and_functions.md
- src/aya/instruction/BlockLiteralInstruction.java
- src/aya/instruction/DictLiteralInstruction.java
- src/aya/instruction/index/GetExprIndexInstruction.java
- src/aya/instruction/op/ColonOps.java
- src/aya/instruction/variable/assignment/TypedAssignment.java
- src/aya/obj/block/BlockUtils.java
- src/aya/obj/block/StaticBlock.java
- src/aya/obj/symbol/SymbolConstants.java
- src/aya/parser/HeaderUtils.java
- src/aya/parser/token/TokenQueue.java
- src/aya/parser/tokens/BlockToken.java
Use `*` in the local declarations section to create a self reference. The name does not need to match the name of the function
```
{n : f*,
.# Parenthesis are optional in Aya; they are sometimes useful for readability
(n 0 =) (n 1 =) | {
n
} {
(n 1 -)f (n 2 -)f +
} .?
}:fib_rec;
```
For golfing purposes, providing a name is optional and will default to `f` is not provided.
```
aya> {a b : * c d, }
{a b : c(0) d(0) f({...}),}
aya> {:*, }
{: f({...}),}
```
The `*` can appear after any name (just like `^`)
```
{arg_a arg_b : local_a capture_a^ self_ref* local_b capture_b^ ... , ...}
```
> Block self reference
